name: Build APK for AllDownloader

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos Ubuntu, ya que es más fácil gestionar SDK y herramientas en Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Android SDK
        run: |
          # Instalar SDK de Android
          sudo apt update
          sudo apt install -y android-sdk

      - name: Accept Android SDK licenses
        run: |
          yes | sudo sdkmanager --licenses

      - name: Install build-tools and platform-tools
        run: |
          # Instalar las herramientas necesarias (versiones especificas)
          sudo sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-33"

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade buildozer

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt  # Asegúrate de tener un requirements.txt con flet, yt-dlp, etc.

      - name: Build APK
        run: |
          # Ejecutar el proceso de construcción
          buildozer android debug  # Asegúrate de que buildozer esté configurado correctamente
