name: Build APK for AllDownloader

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-22.04

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Python, Java, Buildozer y Android SDK
      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y python3-venv openjdk-11-jdk build-essential libffi-dev libssl-dev zlib1g-dev wget unzip
          # Instalar Cython
          pip install cython
          # Instalar herramientas Android SDK
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -P $HOME/android-sdk
          unzip $HOME/android-sdk/commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools
          # Configurar directorio 'latest'
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          rm -rf $HOME/android-sdk/cmdline-tools/cmdline-tools
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          # Aceptar licencias del SDK
          yes | sdkmanager --licenses
          # Instalar dependencias necesarias
          sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-30"
          # Ajustar permisos
          chmod +x $ANDROID_SDK_ROOT/platform-tools/adb
          export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH
          # Instalar buildozer
          pip install --upgrade pip
          pip install buildozer

      # 3. Compilar el APK
      - name: Build APK
        run: |
          buildozer android debug

      # 4. Subir el APK como artefacto
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: AllDownloader-APK
          path: bin/*.apk



